"""2026-01-19

Revision ID: 0188d8065277
Revises: 4a7d4c6764ad
Create Date: 2026-01-19 15:30:26.932199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0188d8065277'
down_revision: Union[str, Sequence[str], None] = '4a7d4c6764ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_k_suggest_answer_review_created', 'knowledge_suggestion', ['answer_status', 'review_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_k_suggest_answer_review_created', table_name='knowledge_suggestion')
    # ### end Alembic commands ###
