"""add_customer

Revision ID: 074d53db845f
Revises: 7b4526cf638c
Create Date: 2026-02-12 10:27:21.602268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074d53db845f'
down_revision: Union[str, Sequence[str], None] = '7b4526cf638c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_number', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inquiry', sa.Column('customer_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_inquiry_customer_id', 'inquiry', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'inquiry', 'customer', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiry', type_='foreignkey')
    op.drop_index('idx_inquiry_customer_id', table_name='inquiry')
    op.drop_column('inquiry', 'customer_id')
    op.drop_table('customer')
    # ### end Alembic commands ###
