"""create api_cost_daily

Revision ID: 096f80a5f8af
Revises: 520251a6c431
Create Date: 2025-10-27 18:03:37.909455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096f80a5f8af'
down_revision: Union[str, Sequence[str], None] = '520251a6c431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cost_daily',
    sa.Column('d', sa.Date(), nullable=False, comment='KST 기준 날짜'),
    sa.Column('product', sa.Text(), nullable=False, comment='llm | embedding | stt '),
    sa.Column('model', sa.Text(), nullable=False, comment='예: gpt-4o-mini, text-embedding-3-small'),
    sa.Column('llm_tokens', sa.BigInteger(), server_default=sa.text('CAST(0 AS BIGINT)'), nullable=False),
    sa.Column('embedding_tokens', sa.BigInteger(), server_default=sa.text('CAST(0 AS BIGINT)'), nullable=False),
    sa.Column('audio_seconds', sa.BigInteger(), server_default=sa.text('CAST(0 AS BIGINT)'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default=sa.text('CAST(0 AS NUMERIC(12, 6))'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_usd >= 0', name='chk_api_cost_nonneg_cost'),
    sa.CheckConstraint('llm_tokens >= 0 AND embedding_tokens >= 0 AND audio_seconds >= 0', name='chk_api_cost_nonneg_usage'),
    sa.PrimaryKeyConstraint('d', 'product', 'model', name='pk_api_cost_daily')
    )
    op.create_index('idx_api_cost_daily_d_desc', 'api_cost_daily', [sa.literal_column('d DESC')], unique=False)
    op.create_index('idx_api_cost_daily_d_product', 'api_cost_daily', ['d', 'product'], unique=False)
    op.create_index('idx_api_cost_daily_product_model', 'api_cost_daily', ['product', 'model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_cost_daily_product_model', table_name='api_cost_daily')
    op.drop_index('idx_api_cost_daily_d_product', table_name='api_cost_daily')
    op.drop_index('idx_api_cost_daily_d_desc', table_name='api_cost_daily')
    op.drop_table('api_cost_daily')
    # ### end Alembic commands ###
