"""add_chat_history_tables

Revision ID: 72dda9c8565e
Revises: 49d1b8e6cbcd
Create Date: 2026-01-15 16:14:13.876707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72dda9c8565e'
down_revision: Union[str, Sequence[str], None] = '49d1b8e6cbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_keyword_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('count >= 0', name='chk_chat_kw_daily_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dt', 'keyword', 'channel', 'category', name='uq_chat_kw_daily')
    )
    op.create_index('idx_chat_kw_daily_dt', 'chat_keyword_daily', ['dt'], unique=False)
    op.create_index('idx_chat_kw_daily_dt_category', 'chat_keyword_daily', ['dt', 'category'], unique=False)
    op.create_index('idx_chat_kw_daily_dt_channel', 'chat_keyword_daily', ['dt', 'channel'], unique=False)
    op.create_index('idx_chat_kw_daily_keyword', 'chat_keyword_daily', ['keyword'], unique=False)
    op.create_table('chat_session_insight',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('first_question', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success','failed')", name='chk_chat_s_insight_status'),
    sa.CheckConstraint('question_count >= 0', name='chk_chat_s_insight_qcount_nonneg'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_chat_s_insight_category_started_at', 'chat_session_insight', ['category', 'started_at'], unique=False)
    op.create_index('idx_chat_s_insight_channel_started_at', 'chat_session_insight', ['channel', 'started_at'], unique=False)
    op.create_index('idx_chat_s_insight_started_at', 'chat_session_insight', ['started_at'], unique=False)
    op.create_index('idx_chat_s_insight_status_started_at', 'chat_session_insight', ['status', 'started_at'], unique=False)
    op.create_table('chat_message_insight',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('is_question', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_chat_m_insight_category_created', 'chat_message_insight', ['category', 'created_at'], unique=False)
    op.create_index('idx_chat_m_insight_is_question_created', 'chat_message_insight', ['is_question', 'created_at'], unique=False)
    op.create_index('idx_chat_m_insight_session_created', 'chat_message_insight', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_inquiry_business_name_created', 'inquiry', ['business_name', 'created_at'], unique=False)
    op.drop_index(op.f('idx_chunk_doc_index'), table_name='knowledge_chunk')
    op.drop_index(op.f('idx_chunk_doc_page'), table_name='knowledge_chunk')
    op.drop_index(op.f('idx_kchunk_created_at'), table_name='knowledge_chunk')
    op.create_index('idx_kchunk_created_at', 'knowledge_chunk', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_kchunk_doc_index', 'knowledge_chunk', ['knowledge_id', 'chunk_index'], unique=False)
    op.create_index('idx_kchunk_doc_page', 'knowledge_chunk', ['knowledge_id', 'page_id'], unique=False)
    op.drop_index(op.f('idx_docpage_doc_page'), table_name='knowledge_page')
    op.create_index('idx_kpage_doc_page', 'knowledge_page', ['knowledge_id', 'page_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kpage_doc_page', table_name='knowledge_page')
    op.create_index(op.f('idx_docpage_doc_page'), 'knowledge_page', ['knowledge_id', 'page_no'], unique=False)
    op.drop_index('idx_kchunk_doc_page', table_name='knowledge_chunk')
    op.drop_index('idx_kchunk_doc_index', table_name='knowledge_chunk')
    op.drop_index('idx_kchunk_created_at', table_name='knowledge_chunk')
    op.create_index(op.f('idx_kchunk_created_at'), 'knowledge_chunk', ['created_at'], unique=False)
    op.create_index(op.f('idx_chunk_doc_page'), 'knowledge_chunk', ['knowledge_id', 'page_id'], unique=False)
    op.create_index(op.f('idx_chunk_doc_index'), 'knowledge_chunk', ['knowledge_id', 'chunk_index'], unique=False)
    op.drop_index('idx_inquiry_business_name_created', table_name='inquiry')
    op.drop_index('idx_chat_m_insight_session_created', table_name='chat_message_insight')
    op.drop_index('idx_chat_m_insight_is_question_created', table_name='chat_message_insight')
    op.drop_index('idx_chat_m_insight_category_created', table_name='chat_message_insight')
    op.drop_table('chat_message_insight')
    op.drop_index('idx_chat_s_insight_status_started_at', table_name='chat_session_insight')
    op.drop_index('idx_chat_s_insight_started_at', table_name='chat_session_insight')
    op.drop_index('idx_chat_s_insight_channel_started_at', table_name='chat_session_insight')
    op.drop_index('idx_chat_s_insight_category_started_at', table_name='chat_session_insight')
    op.drop_table('chat_session_insight')
    op.drop_index('idx_chat_kw_daily_keyword', table_name='chat_keyword_daily')
    op.drop_index('idx_chat_kw_daily_dt_channel', table_name='chat_keyword_daily')
    op.drop_index('idx_chat_kw_daily_dt_category', table_name='chat_keyword_daily')
    op.drop_index('idx_chat_kw_daily_dt', table_name='chat_keyword_daily')
    op.drop_table('chat_keyword_daily')
    # ### end Alembic commands ###
