"""remove message_id and comment from feedback

Revision ID: 8cfcef3956eb
Revises: 6b03b7952219
Create Date: 2025-10-31 15:28:46.591358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfcef3956eb'
down_revision: Union[str, Sequence[str], None] = '6b03b7952219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_feedback_message'), table_name='feedback')
    op.drop_index(op.f('uq_feedback_message_once'), table_name='feedback', postgresql_where='(message_id IS NOT NULL)')
    op.drop_constraint(op.f('feedback_message_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'comment')
    op.drop_column('feedback', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('feedback_message_id_fkey'), 'feedback', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_feedback_message_once'), 'feedback', ['message_id'], unique=True, postgresql_where='(message_id IS NOT NULL)')
    op.create_index(op.f('idx_feedback_message'), 'feedback', ['message_id'], unique=False)
    op.alter_column('feedback', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
