"""new default

Revision ID: af06cfd15e72
Revises: 096f80a5f8af
Create Date: 2025-10-28 11:58:21.743989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af06cfd15e72'
down_revision: Union[str, Sequence[str], None] = '096f80a5f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_cost_daily', 'product',
               existing_type=sa.TEXT(),
               comment='llm | embedding | stt ',
               existing_comment='llm | embedding | stt | tts | image',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_cost_daily', 'product',
               existing_type=sa.TEXT(),
               comment='llm | embedding | stt | tts | image',
               existing_comment='llm | embedding | stt ',
               existing_nullable=False)
    # ### end Alembic commands ###
